name = "SatisfiabilityInterface"
uuid = "f4c7ffe1-8047-4e71-98df-f1c7b392bec0"
authors = ["David P. Sanders <dpsanders@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
ModelingToolkit = "4.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
